Repository siddharth25pandey/CPP-Programming, pull requests merged in 2020-10, with the labels that each got.

#149 LCA_of_BinaryTree
  Trees Algorithm/LCA_of_BinaryTree.cpp
Labels: hacktoberfest-accepted

#151 check_if_BinaryTree_a_BST
  Trees Algorithm/check_if_BinaryTree_a_BST.cpp
Labels: hacktoberfest-accepted

#57 Lee alogrithm branch
  Maze Routing Algorithms/lee_alogrithm
  Maze Routing Algorithms/lee_alogrithm.cpp
Labels: hacktoberfest-accepted

#153 Added Codeforces Dynamic Programming Problems
  DP/BearCompressing.cpp
  DP/LittleGirlMaxXOR.cpp
  DP/README.md
  DP/SimpleStrings.cpp
  DP/TwoSubstrings.cpp
Labels: Modification required, hacktoberfest-accepted

#150 LCA_of_BST
  Trees Algorithm/LCA_of_BST.cpp
Labels: duplicate

#159 Subset Sum problem of DP
  Subset_sum_problem.cpp
Labels: hacktoberfest-accepted

#161 Comb Sort
  Sorting Algorithms/CombSort.cpp
Labels: hacktoberfest-accepted

#163 Red Black Tree
  Trees Algorithm/Red_Black_Tree.cpp
Labels: hacktoberfest-accepted

#165 Create exampleFuctionOverloading.cpp
  Function overloading/exampleFuctionOverloading.cpp
Labels: hacktoberfest-accepted

#166 Added Min Jumps DP problem
  MinJumps_DP.cpp
Labels: hacktoberfest-accepted

#170 Added the Min_Jumps DP Prog
  DP/MinJumps_DP.cpp
Labels: hacktoberfest-accepted

#171 Reverse a linked list
  Linked List Algo/ReverseALinkedList.cpp
  Linked List Algo/StackFromLinkedList.cpp
Labels: Modification required, hacktoberfest-accepted

#173 Added FloydWarshall Algorithm and Kruskal Algorithm
  Graph Algorithm/FloydWarshallAlgorithm.cpp
  Graph Algorithm/KruskalAlgorithm.cpp.cpp
Labels: hacktoberfest-accepted

#174 Jump-Search,Exponential Search,Interpolation Search
  Searching Algo/exponential_search.cpp
  Searching Algo/interpolation_search.cpp
  Searching Algo/jump_search.cpp
Labels: hacktoberfest-accepted

#180 Create primitiveCalculater.cpp
  DP/primitiveCalculater.cpp
Labels: Hacktoberfest 2020, hacktoberfest-accepted
