Repository siddharth25pandey/CPP-Programming, pull requests merged in 2022-10, with the labels that each got.

#410 Divide_two_Integers
  Maths/divide_two_integers.cpp
Labels: Hacktoberfest 2022, hacktoberfest

#408 Created solution for Find the first circular tour that visits all petrol pumps
  Greedy Algorithms/visit-all-stations.cpp
Labels: Hacktoberfest 2022, hacktoberfest

#401 Create Sum_of_numbers_string.cpp
  Maths/Sum_of_numbers_string.cpp
Labels: Hacktoberfest 2022, hacktoberfest

#402 I have Added 2 files for kahn's algorithm #233
  Graph Algorithm/Kahn's algorithm.cpp
  Graph Algorithm/Kahn’s Topological Sort Algorithm.cpp
Labels: Hacktoberfest 2022, hacktoberfest

#407 Create print-all-anagrams.cpp
  print-all-anagrams.cpp
Labels: Hacktoberfest 2022, hacktoberfest

#412 Added MaxDifferenceInArray.cpp
  Searching Algo/MaxDifferenceInArray.cpp
Labels: Hacktoberfest 2022, hacktoberfest

#421 add_two_numbers.cpp
  Linked List Algo/add_two_numbers.cpp
Labels: Hacktoberfest 2022, hacktoberfest

#422 Decode Ways
  DP - LEETCODE/Decode Ways.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#423 Longest Increasing Path in a Matrix
  DP - LEETCODE/Longest Increasing Path in a Matrix.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#424 Partition Equal Subset Sum
  DP - LEETCODE/Partition Equal Subset Sum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#425 Time Needed to Rearrange a Binary String
  DP - LEETCODE/Time Needed to Rearrange a Binary String.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#428 Minimum Path Cost in a Grid
  DP - LEETCODE/minimum-path-cost-in-a-grid.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#429 Create Subarray_with_givensum.cpp
  Binary Search/Subarray_with_givensum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#430 Create Allocate_minimum_no_of_pages.cpp
  Binary Search/Allocate_minimum_no_of_pages.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#432 added string folder with code and also added some code in recursion folder
  Recursion/checkPalindrome.cpp
  Recursion/first_last_occur.cpp
  strings/break_words.cpp
  strings/check_anagram.cpp
  strings/equalstacks.cpp
  strings/lexicographic_rank_string.cpp
  strings/multiply2numericalstrings.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#436 Create Reorder_array_with_indexes.cpp
  Arrays/Reorder_array_with_indexes.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#437 Create Checking_palindrome_using_Recursion.cpp
  Recursion/Checking_palindrome_using_Recursion.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#438 Add solution of problem related to binarySearch
  Binary Search/BookAllocation.cpp
  Binary Search/FirstAndLastElement.cpp
  Binary Search/PeakElementMountainArray.cpp
  Binary Search/TotalOccurence.cpp
  Binary Search/binarySearch.cpp
  Binary Search/pitvot.cpp
  Binary Search/squareRoot.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#441 Ashutosh Shukla | Recursion | Added Palindrome Check using Recursion
  Recursion/Palindrome_Check_using _Recursion.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#442 Kiriotheo patch 1
  Inline functions/README.md
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#495 Median of Two Sorted Arrays
  Maths/Median of Two Sorted Arrays.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#496 Largest Rectangle in Histogram
  Stack Algorithims/Largest Rectangle in Histogram.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#497 Minimum Window Substring
  SLIDING WINDOW/Minimum Window Substring.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#498 Binary Tree Maximum Path Sum
  Trees Algorithm/Binary Tree Maximum Path Sum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#448 Added missing_number_in_array.cpp
  Searching Algo/missing_number_in_array.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#449 Detect Removal of Loop
  Linked List Algo/Detect_Removal_of_loop.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#452 Create SummationOfLists.cpp
  Linked List Algo/SummationOfLists.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#453 Added Binary Search code
  Binary Search/Binary_search.cpp
  Binary Search/Binary_search.exe
  Binary Search/Practice_questions.txt
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#457 Binary search implementation code added
  Binary Search/BInary_search_iterative.cpp
  Binary Search/Binary_search_recursve.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#458 Search in a 2d matrix
  Binary Search/Search_in_2d_matrix.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#461 added linkedlistmenu.cpp
  Linked List Algo/linkedlistmenu.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#464 Create robinround.cpp
  DP/robinround.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#469 Added three greedy approaches
  Greedy Algorithms/134. Gas Station.cpp
  Greedy Algorithms/1561. Max_Coins_You_Can_Get.cpp
  Greedy Algorithms/1642. Furthest_Building_You_Can_Reach.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#470 KMP ALGORIHTM ADDED
  strings/KMP algorithm.cpp
  strings/Minimum characters to be added at front to make string palindrome__ON KMP ALGORITHM.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#471 An Important Leetcode CPP Question
  Leetcode/maximum-score-from-performing-multiplication-operations.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#472 Added longest path with different adjacent characters.cpp
  DP - LEETCODE/Longest Path with Different Adjacent Characters.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#473 bubble sort
  Arrays/bubblesort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#474 Added Running Sum in 1D Array problem
  DP - LEETCODE/RunningSum1D.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#475 added Grade_The_Steel problem
  Arrays/A_Beautiful_Matrix.cpp
  Arrays/Grade_The_Steel.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#476 Added Postfix to infix conversion using Stack
  Stack Algorithims/PostfixToInfix.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#477 Added longest palindromic substring in DP Leetcode
  DP - LEETCODE/Longest palindromic substring
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#479 added Product of Array Except Self
  Arrays/productofArray_exceptSelf
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#481 Kushagra | LongestCommonPrefix.cpp
  strings/LongestCommonPrefix.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#482 Searching element and calculate distance of element from source in graph using DFS
  Graph Algorithm/Dfs_search.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#484 Create PrintArray.cpp
  Arrays/PrintArray.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#485 Calculator.cpp
  .DS_Store
  Maths/Calculator.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#486 Create chain_hashing.cpp
  hashing/chain_hashing.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#489 Added more problems and solution in Linked list
  Linked List Algo/ReverseLinkedList.cpp
  Linked List Algo/insertAtTail.cpp
  Linked List Algo/insertAthead.cpp
  Linked List Algo/kReverse.cpp
  Linked List Algo/lenghOfLinkedList.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#490 added linkedlist insertion program for all positions
  Linked List Algo/linkedlistinsert.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#492 added problems in arrays
  Arrays/FirstAndLastOcc.cpp
  Arrays/MaxMinOfArray.cpp
  Arrays/findPivot.cpp
  Arrays/peekInMountain.cpp
  Arrays/reverseAnArray.cpp
  Arrays/totalNumberOfOcc.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#493 Create rotate_array_by_k.cpp
  Arrays/rotate_array_by_k.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#494 Create subarray with given sum.cpp
  Arrays/subarray with given sum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#500 solve where is the marble problem
  Where_is_the_Marble.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#512 Create Split Array With Same Average.cpp
  Arrays/Split Array With Same Average.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#516 Create The painter’s partition problem.cpp
  Binary Search/The painter’s partition problem.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#517 Master
  hashing/LRU Cache.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#439 reverse array
  DP/reverseArray.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#539 Without using a semicolon, print all natural integers up to N. The co…
  Tricky Programs/1.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#540 Added Minimum Operations to Make a Uni-Value Grid using cpp
  DP - LEETCODE/MedianofSortedArrays.cpp
  DP - LEETCODE/MinimumOperations_toMake_Uni-ValueGrid.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#542 added merging of 2 sorted arrays
  Arrays/merge_2_sorted_arrays.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#543 created Modular Node.cpp
  Linked List Algo/Modular Node.cpp
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#546 Create Kadane's Algorithm.cpp
  Arrays/Kadane's  Algorithm.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#547 C++ Patterns
  C++ Pattern problem/TwetlthPattren.cpp
  C++ Pattern problem/eightPattren.cpp
  C++ Pattern problem/elventhPattren.cpp
  C++ Pattern problem/fifthPattren.cpp
  C++ Pattern problem/fourthpattren.cpp
  C++ Pattern problem/fristPattren.cpp
  C++ Pattern problem/ninthPattren.cpp
  C++ Pattern problem/secondPattren.cpp
  C++ Pattern problem/sevenPattren.cpp
  C++ Pattern problem/sixthPattren.cpp
  C++ Pattern problem/tempCodeRunnerFile.cpp
  C++ Pattern problem/tenthPattren.cpp
  C++ Pattern problem/thirdpattren.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#548 Create Minimize_the_maximum_diff_between_heights.cpp
  Arrays/Minimize_the_maximum_diff_between_heights.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#549 Create reverse word in a given string.cpp
  strings/reverse word in a given string.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#550 Create MatrixMultiplication.cpp
  Arrays/MatrixMultiplication.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#551 Create Move Zeroes To The End.cpp
  Arrays/Move Zeroes To The End.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#552 Create SumOfMatrix.cpp
  Arrays/SumOfMatrix.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#553 Create Find Minimum in Rotated Sorted Array.cpp
  Leetcode/Find Minimum in Rotated Sorted Array.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#554 added 3d dp question
  DP - LEETCODE/Paths in matrix whose sum is divisible by k.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#563 Bellman Ford
  DP/Bellman Ford.cpp
  Maths/ceiling sum.cpp
  Maths/factorial of a number.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#574 Added Two Sum IV - Input is a BST using CPP
  DP - LEETCODE/TwoSum_IV_Input_is_a_BST.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#571 Added the new file for the Water Jug program in C++
  Graph Algorithm/Water_jug.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#576 Added bitonicsort.cpp
  Maths/pattern.cpp
  Sorting Algorithms/bitonic_sort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#578 MaxSubArraySum.cpp : A leetcode solution
  DP - LEETCODE/MaxSubArraySum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#585 longest_increasing_subsequence_DP
  DP/longest_increasing_subsequence.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#600 Master
  DP/Count_ways_to_reach_nth_stair.cpp
  bit_manipulation/Repeated DNA sequences
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#602 Code for Combination Sum
  Backtrack/Combination_Sum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#604 Create Palindrome Number.cpp
  Leetcode/Palindrome Number.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#605 Added code for adding two binary string problem
  strings/add_two_binary_string.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#607 Added code of creating custom stack in cpp
  Stack Algorithims/Create Custom Stack.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#608 Moore Majority voter Algo
  Arrays/Boyer-Moore-Majority-Voting-Algo.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#617 Create letter_combination_of_a_phone_number.cpp
  strings/letter_combination_of_a_phone_number.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#618 Added Largest Perimeter Triangle using CPP
  DP - LEETCODE/Largest_Perimeter_Triangle.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#619 Added Valid Parenthesis generator code
  Recursion/Generate_Parentheses.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#621 Added Doodles for Algorithms
  DSA Doodles/.DS_Store
  DSA Doodles/algorithms/.DS_Store
  DSA Doodles/algorithms/README.md
  DSA Doodles/algorithms/png/algorithm101_Array.png
  DSA Doodles/algorithms/png/algorithm101_BST_01.png
  DSA Doodles/algorithms/png/algorithm101_BST_02.png
  DSA Doodles/algorithms/png/algorithm101_BigO_01.png
  DSA Doodles/algorithms/png/algorithm101_BigO_02.png
  DSA Doodles/algorithms/png/algorithm101_Hash_Table_01.png
  DSA Doodles/algorithms/png/algorithm101_Hash_Table_02.png
  DSA Doodles/algorithms/png/algorithm101_Heap_01.png
  DSA Doodles/algorithms/png/algorithm101_Heap_02.png
  DSA Doodles/algorithms/png/algorithm101_Linked_List.png
  DSA Doodles/algorithms/png/algorithm101_Queue.png
  DSA Doodles/algorithms/png/algorithm101_Stack.png
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#648 Added problem sum of sub array ranges in C++
  Arrays/sum_of_subarray_ranges.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#649 Create Bucket sort.cpp
  Sorting Algorithms/Bucket sort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#650 Create count_numberOfHops.cpp
  DP/count_numberOfHops.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#651 Create TYPE_CONVERSION.cpp
  Function overloading/TYPE_CONVERSION.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#653 Added file for problem multiply two strings
  Arrays/Minimum_swaps_to_sortArray.cpp
  strings/Multiply_two_large_number.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#654 Added file of 0-1_knapsack.cpp for DP Section
  DP/0-1_knapsack.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#656 Create maximum_subarray.cpp
  Leetcode/maximum_subarray.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#659 kahn's sort algorithm added
  Graph Algorithm/kahn's sort algorithm.cpp
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#660 Master
  Recursion/Josephus Problem.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#663 Added string code
  strings/sum_of_two_large_numbers.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#664 Payonidhi|BinarySearchonLinkedList|
  Binary Search/BinarySearchonLinkedList.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#668 Create HeartPattern.cpp
  C++ Pattern problem/HeartPattern.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#669 Efficient approach for check_anagram.cpp
  strings/check_anagram.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#670 Create shortest-unsorted-continuous-subarray.cpp
  Arrays/shortest-unsorted-continuous-subarray.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#673 Vertical_Tree_Traversal
  Trees Algorithm/Vertical_Treversal_Of_Binary_Tree.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#675 Cocktail Sort
  Sorting Algorithms/CoctailSort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#680 Create AnimationPattern.cpp
  C++ Pattern problem/AnimationPattern.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#682 Create Burst Balloons.cpp
  DP/Burst Balloons.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#707 Merge Sort
  Sorting Algorithms/Merge_Sort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#712 Create Palindrome_Partitioning_ II.cpp
  DP/Palindrome_Partitioning_ II.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#713 Create Quadratic_Probing.cpp
  hashing/Quadratic_Probing.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#714 Bottom View of Binary Tree
  Trees Algorithm/Bottom_View_of_Binary_Tree.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#721 inverse_pyramid
  C++ Pattern problem/Inverse_Star_Pyramid.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#720 Added a codechef graph problem chess knight move
  Graph Algorithm/codechef_chess_knight_move.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#718 anubhav soni changes done in contact us page in the cpp-website
  C++ Pattern problem/PascalTriangle.cpp
  cpp-website/package-lock.json
  cpp-website/package.json
  cpp-website/src/components/Contactus.js
  cpp-website/src/components/contactus.css
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#717 Archisman Dawn | DP-LEETCODE , Trees Algorithm | Added 0-1 knapsack …
  DP - LEETCODE/0-1_Knapsack.cpp
  DP - LEETCODE/Coin-Change.cpp
  DP - LEETCODE/Egg_drop.cpp
  Trees Algorithm/Unique_BST_II.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#716 added spiralmatrix file
  Arrays/spiral_matrices.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#594 Added InsertionSort.cpp
  Sorting Algorithms/InsertionSort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#676 Create GameOfLife
  Leetcode/289. Game_Of_Life.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#734 added diamond pattern
  C++ Pattern problem/diamond_pattern.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#738 Create Invert_alternate_levels_of_a_perfect_binary_tree.cpp
  Trees Algorithm/Invert_alternate_levels_of_a_perfect_binary_tree.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#739 Add files via upload
  Sorting Algorithms/DNFsort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest

#746 Home and About page updated.
  cpp-website/public/index.html
  cpp-website/src/App.css
  cpp-website/src/components/About/About.css
  cpp-website/src/components/About/About.js
  cpp-website/src/components/Home/Home.js
  cpp-website/src/components/Home/home.css
  cpp-website/src/components/Navbar/Navbar.css
  cpp-website/src/files/community.png
  cpp-website/src/files/contribute.png
  cpp-website/src/files/explore.png
  cpp-website/src/files/pngwing.com (3).png
Labels: hacktoberfest-accepted, Hacktoberfest 2022, hacktoberfest
